### ISSUE TITLE
.pickle file in CamVid data

### ISSUE THREAD

**Issue by yesvalent** [jendrikjoe/SegNet#1]
Error( Windows10, Eclipse, pydev):
  File "D:\.............\src\Data\Datasets.py", line 469, in generator
    with open(pickleName, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'd:/dataCV/CamVid/LabeledApproved_full/701_StillsRaw_full\\0016E5_00630_L.pickle'

please tell me what is it /LabeledApproved_full/701_StillsRaw_full  in CamVid and ..._L.pickle?

**Comment by jendrikjoe** [comment]
Hey @yesvalent,

normally this exception should be caught by the except statement.
The except statement then reads in the colored annotated file extracts the classes from it and stores a .pickle file with the class ids stored. This saves you later a lot of time as this conversion takes quite long.
The issue you are having might be related to using Windows and getting paths with backslashes from glob. I posted code which replaces the backslashes. 
Can you pull it and tell me if it resolves your bug? :)

Cheers,

Jendrik

**Comment by yesvalent** [comment]
I myself replace
    ##camVid = CamVid('../data/CamVid', numberOfClasses=numberOfClasses, samplesPerBatch=1)
by
    camVid = CamVid('d:/dataCV/CamVid', numberOfClasses=numberOfClasses, samplesPerBatch=1)

and this work:
class CamVid(Dataset):
    def __init__(self, path, samplesPerBatch, **kwargs):
        super(CamVid, self).__init__(path=path)
        imageList = glob.glob(self.path + '/701_StillsRaw_full/*.png')

I see in debug  list (imageList) from 701 files
it's not about backslashes, but  subdirectory /LabeledApproved_full/701_StillsRaw_full\\
I have to create it?

**Comment by jendrikjoe** [comment]
I think the bug lies earlier in the code in line 369 and 370, but it only causes and error later. 
None of the entries in imageList should contain a backslash. If they do, pleas pull the latest commit I made. That should solve. 
The file it loads shouldn't be 'd:/dataCV/CamVid/LabeledApproved_full/701_StillsRaw_full\0016E5_00630_L.pickle', but instead 'd:/dataCV/CamVid/LabeledApproved_full/0016E5_00630_L.pickle'.
The backslash in the path leads to wrong parsing as I currently rely on detecting the / when I am changing the file names in the code :)
This is migrate in the newest version as I replace all the backslashes which glob is returning with slashes. Then the renaming of the files works again and the loading of the images should works as well :)

**Comment by yesvalent** [comment]
Thank you.
i insert
      imageList = [path.replace('\\', '/') for path in imageList]
and this work
